spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
        